spring:
    application:
        name: virality
    datasource:
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/virality_db
    jpa:
        hibernate:
            ddl-auto: update